
import { Language, TranslationStrings } from './types';

export const COLORS = {
  POSTE_YELLOW: '#FFD700',
  POSTE_BLUE: '#003366',
  POSTE_BLUE_LIGHT: '#004A8D',
};

export const TRANSLATIONS: Record<Language, TranslationStrings> = {
  ar: {
    title: 'بريدي RIP',
    subtitle: 'محول رقم الحساب الجاري (CCP) إلى رقم التعريف البريدي (RIP)',
    ccpInputLabel: 'رقم الحساب الجاري (CCP)',
    nameInputLabel: 'الاسم (اختياري للحفظ)',
    calculateBtn: 'تحويل واستخراج المفاتيح',
    saveBtn: 'حفظ في المفضلة',
    historyTitle: 'الحسابات المحفوظة',
    noHistory: 'لا توجد حسابات محفوظة بعد.',
    ccpKey: 'مفتاح CCP',
    ripKey: 'مفتاح RIP',
    fullRip: 'رقم RIP الكامل',
    copySuccess: 'تم النسخ بنجاح!',
    deleteConfirm: 'هل أنت متأكد من حذف هذا الحساب؟',
    placeholderCcp: 'أدخل رقم الحساب',
    placeholderName: 'أدخل اسم الحساب (اختياري)',
    invalidCcp: 'يرجى إدخال رقم CCP صحيح',
    footer: 'جميع الحقوق محفوظة © بريد الجزائر (أداة مساعدة)',
    aiHelper: '',
    offlineReady: 'يعمل في وضع عدم الاتصال (أوفلاين) - جميع العمليات آمنة ومحلية',
    onlineStatus: 'متصل بالإنترنت',
    feeCalculatorTitle: 'حاسبة رسوم سحب الأموال الجارية (CCP)',
    amountLabel: 'المبلغ المراد سحبه (بالدينار الجزائري دج)',
    calculatedFee: 'رسوم البريد المستقطعة',
    payoutAmount: 'الصافي السائل المستلم',
    requiredBalance: 'الرصيد المطلوب توفره في الحساب',
    privacyModalTitle: 'حول التطبيق والسرية والأمان',
    privacyModalText: 'هذا التطبيق مجاني، آمن 100% ويعمل بالكامل بدون الحاجة للإنترنت. تتم جميع الحسابات محلياً داخل جهازك دون إرسال أي بيانات أو أرقام حسابات إلى أي خادم خارجي. خصوصيتك محمية بالكامل ولا يتم تتبع أو جمع أي معلومات عن المستخدمين ويعالج البيانات محلياً في الهاتف دون إرسال أي معلومات.',
    devNameLabel: 'مطور التطبيق',
    shareBtn: 'مشاركة كارت الحساب',
    bracketInfo: 'جدول تصاعدي رسمي لرسوم السحب لبريد الجزائر',
    backupBtn: 'تصدير نسخة احتياطية (تنزيل ملف)',
    restoreBtn: 'استيراد نسخة احتياطية (تحديد ملف)',
    backupSuccess: 'تم تصدير النسخة الاحتياطية بنجاح بنسق ملف JSON !',
    restoreSuccess: 'تمت استعادة الحسابات بنجاح من النسخة الاحتياطية !',
    restoreError: 'عذراً، الملف المحدد غير صالح أو تالف.',
    backupSectionTitle: 'النسخ الاحتياطي واستعادة البيانات',
    historyLogTitle: 'سجل العمليات الأخير',
    noHistoryLog: 'لا توجد عمليات سابقة في السجل دائمًا آمن ومحلي.',
    clearHistoryBtn: 'مسح السجل بالكامل'
  },
  fr: {
    title: 'Baridi RIP',
    subtitle: 'Convertisseur CCP vers RIP et calculateur de clés',
    ccpInputLabel: 'Numéro de compte CCP',
    nameInputLabel: 'Nom (optionnel pour sauvegarde)',
    calculateBtn: 'Convertir & Calculer',
    saveBtn: 'Sauvegarder',
    historyTitle: 'Comptes enregistrés',
    noHistory: 'Aucun compte enregistré pour le moment.',
    ccpKey: 'Clé CCP',
    ripKey: 'Clé RIP',
    fullRip: 'Numéro RIP complet',
    copySuccess: 'Copié avec succès !',
    deleteConfirm: 'Voulez-vous supprimer ce compte ?',
    placeholderCcp: 'Entrez le numéro de compte',
    placeholderName: 'Entrez le nom du compte (optionnel)',
    invalidCcp: 'Veuillez entrer un numéro CCP valide',
    footer: 'Tous droits réservés © Algérie Poste (Outil d\'aide)',
    aiHelper: '',
    offlineReady: 'Mode hors-ligne actif - Calculs 100% locaux et sécurisés',
    onlineStatus: 'En ligne',
    feeCalculatorTitle: 'Calculateur de Taxe de Retrait CCP',
    amountLabel: 'Montant à retirer (DZD)',
    calculatedFee: 'Taxe de retrait déduite',
    payoutAmount: 'Montant net reçu',
    requiredBalance: 'Solde requis sur le compte',
    privacyModalTitle: 'À propos, Confidentialité & Sécurité',
    privacyModalText: 'Cette application est gratuite, 100% sécurisée et fonctionne entièrement hors-ligne. Tous les calculs sont effectués localement sur votre appareil sans envoyer aucune donnée ou numéro de compte à un serveur externe. Votre vie privée est garantie et aucune donnée personnelle n\'est collectée.',
    devNameLabel: 'Développeur',
    shareBtn: 'Partager la fiche de compte',
    bracketInfo: 'Tranches officielles des taxes de retrait Algérie Poste',
    backupBtn: 'Exporter une sauvegarde (Télécharger)',
    restoreBtn: 'Importer une sauvegarde (Choisir un fichier)',
    backupSuccess: 'Sauvegarde exportée avec succès sous format JSON !',
    restoreSuccess: 'Comptes restaurés avec succès depuis la sauvegarde !',
    restoreError: 'Désolé, le fichier sélectionné est invalide ou corrompu.',
    backupSectionTitle: 'Sauvegarde & Restauration des données',
    historyLogTitle: 'Historique récent',
    noHistoryLog: 'Aucune conversion récente (100% s@curisé & local).',
    clearHistoryBtn: 'Effacer l\'historique'
  },
  en: {
    title: 'Baridi RIP',
    subtitle: 'Algerian CCP to RIP Converter & Key Generator',
    ccpInputLabel: 'CCP Account Number',
    nameInputLabel: 'Name (optional for saving)',
    calculateBtn: 'Convert & Calculate',
    saveBtn: 'Save to Favorites',
    historyTitle: 'Saved Accounts',
    noHistory: 'No accounts saved yet.',
    ccpKey: 'CCP Key',
    ripKey: 'RIP Key',
    fullRip: 'Full RIP Number',
    copySuccess: 'Copied to clipboard!',
    deleteConfirm: 'Are you sure you want to delete this account?',
    placeholderCcp: 'Enter account number',
    placeholderName: 'Enter account name (optional)',
    invalidCcp: 'Please enter a valid CCP number',
    footer: 'All rights reserved © Algérie Poste (Utility tool)',
    aiHelper: '',
    offlineReady: 'Offline Mode Ready - 100% local and secure calculation',
    onlineStatus: 'Online',
    feeCalculatorTitle: 'CCP Cash Withdrawal Fee Calculator',
    amountLabel: 'Amount to withdraw (DZD)',
    calculatedFee: 'Deducted withdrawal fee',
    payoutAmount: 'Net amount received',
    requiredBalance: 'Required minimum account balance',
    privacyModalTitle: 'About, Privacy & Security',
    privacyModalText: 'This application is free, 100% secure, and works fully offline. All calculations are performed locally on your device without sending any account details to an external server. Your privacy is fully guaranteed, and no personal data is collected.',
    devNameLabel: 'Developer',
    shareBtn: 'Share Account Card',
    bracketInfo: 'Official Algérie Poste withdrawal fee brackets',
    backupBtn: 'Export Backup (Download JSON)',
    restoreBtn: 'Import Backup (Select File)',
    backupSuccess: 'Backup exported successfully as JSON!',
    restoreSuccess: 'Accounts successfully restored from backup!',
    restoreError: 'Sorry, the selected file is invalid or corrupted.',
    backupSectionTitle: 'Backup & Restore Data',
    historyLogTitle: 'Recent Calculations History',
    noHistoryLog: 'No recent conversions found in your local history.',
    clearHistoryBtn: 'Clear History'
  }
};
